### ISSUE TITLE
0.4.0 cause Safari crash too offend

### ISSUE THREAD

**Issue by cyberjom** [redsquirrel/safariwatir#8] opened 2010-11-16 10:24 UTC
After update from 0.3.8 to 0.4.0  all my mac with Safari 5.0.2 (6533.18.5) crash randomly.
I can't make my all my test pass. every time the crash occur it's in different action. And I can run test pass at the specific point. Now I have try quit safari every feature but still not good enough.

**Comment by charley** [comment] 2010-11-19 21:42
I've closed this issue, as I'm not sure how best to help you on this without more information. If you can get a bit more specific and try to narrow down the cause that would be helpful. Random crashes aren't very helpful, possibly you can include a stack trace? Otherwise, I've run tests using both 0.3.8 and 0.4.0 and not seeing anything unusual.

**Comment by cyberjom** [comment] 2010-11-20 04:56
Thank you for you time. I will try it more to see what is the cause of the crash and report you again. Anyway thank for your work.

**Closed as completed** 2010-11-20 05:38 UTC
